# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d07684e113e1af3e5f8cdebbf5e0f7ee61ac0ea801097385f3793ee6aec3f69fcfdad1f40fbc825d84e29886d146fb3ee13f87efc6725262b0d37e55b0b35a9c

test:
  secret_key_base: 5d0859bc0756ce5af76f504971e3a7e08c29a4198efbd8b7edbb73e6cece3a9b744520b6a6a6422580659136bdeed41a0c6f9dd33755493fb694f41e2d760ae2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
